### ISSUE TITLE
Handling "vdw 0.0 0.0"

### ISSUE THREAD

**Issue by alexmaryewski** [Molecolab-Pisa/OpenMMPol#1]
**Issue**: having more than one instance of "vdw 0.0 0.0" in key files results in non-bonded term evaluating to NaN.

Example with DFTB+ is attached.
[example.tar.gz](https://github.com/Molecolab-Pisa/OpenMMPol/files/15092397/example.tar.gz)

**Comment by mattiabondanza** [comment]
Solved with commit https://github.com/Molecolab-Pisa/OpenMMPol/commit/c72728f8eb42a36580e09fe0d3e6a351dcfc4118 @alexmaryewski
