### ISSUE TITLE
Multipoles initializing to NaN in high-symmetry systems

### ISSUE THREAD

**Issue by alexmaryewski** [Molecolab-Pisa/OpenMMPol#2]
**Issue**: for certain systems with high degree of symmetry, multipoles initialize to NaN. Adding random numerical noise (~1e-5) seems to help.

Example is attached.
[example.tar.gz](https://github.com/Molecolab-Pisa/OpenMMPol/files/15108694/example.tar.gz)

**Comment by mattiabondanza** [comment]
Thanks for the bug report. It was a numerical problem for atoms perfectly aligned on x axis. This should solve #efccfd6
